# Generated by Django 4.0.1 on 2022-01-31 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Book_App', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='Is_Active',
            field=models.BooleanField(default=True),
        ),
    ]
